language: python
cache: pip
python:
  - "3.6"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  - mypy lemon --ignore-missing-imports
  - pycodestyle --exclude docs/ --ignore E501
  - coverage run --source=lemon setup.py test
  - coveralls
notifications:
  webhooks: https://app.fossa.io/hooks/travisci