language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - coverage run --source=lemon setup.py test
  - coveralls
  - pycodestyle --exclude docs/ --ignore E501
notifications:
  webhooks: https://app.fossa.io/hooks/travisci
