version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.5
      - test-3.6
      - test-3.7
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6
    environment:
      COVERALLS: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r requirements.txt
           curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - save_cache:
          paths:
            - ./venv
          key: v1-dep-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Run check
          command: |
            . venv/bin/activate
            mypy lemon --ignore-missing-imports
            pycodestyle --exclude pycodestyle --exclude venv,.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,docs,.eggs  --ignore E501
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            coverage run --source=lemon setup.py test
            [[ $COVERALLS == true ]] && coveralls || true
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5
    environment:
      COVERALLS: false
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7
    environment:
      COVERALLS: false
